[package]
name = "veto"
version = "0.2.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"
readme = "README.md"
description = "A lightweight, log file based IP blocker with focus on simplicity and speed."
homepage = "https://github.com/dnaka91/veto"
repository = "https://github.com/dnaka91/veto"

[package.metadata.deb]
maintainer-scripts = "debian/"
systemd-units = { enable = false }
license-file = ["LICENSE", "0"]
depends = "$auto, ipset"
assets = [
    ["target/release/veto", "/usr/bin/veto", "755"],
    ["README.md", "/usr/share/doc/veto/README.md", "644"],
    ["sample.toml", "/etc/veto/config.toml.sample", "644"],
]

[dependencies]
ahash = "0.7.6"
aho-corasick = "0.7.18"
anyhow = "1.0.58"
bincode = "1.3.3"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.2.6", features = ["derive", "env"] }
crossbeam-channel = "0.5.5"
ctrlc = { version = "3.2.2", features = ["termination"] }
dotenvy = "0.15.1"
flate2 = "1.0.24"
humantime = "2.1.0"
indexmap = { version = "1.9.1", features = ["serde-1"] }
ipnetwork = "0.19.0"
itertools = "0.10.3"
log = "0.4.17"
notify = "5.0.0-pre.15"
parking_lot = "0.12.1"
phf = { version = "0.10.1", features = ["macros"] }
pretty_env_logger = "0.4.0"
regex = "1.5.6"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"
which = "4.2.5"

[dev-dependencies]
criterion = "0.3.5"

[profile.release]
lto = true

[[bench]]
name = "matcher"
harness = false
