[package]
name = "veto"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-only"
readme = "README.md"
description = "A lightweight, log files based IP blocker with focus on simplicity and speed."
homepage = "https://github.com/dnaka91/veto"
repository = "https://github.com/dnaka91/veto"

[package.metadata.deb]
maintainer-scripts = "debian/"
systemd-units = { enable = false }
license-file = ["LICENSE", "0"]
depends = "$auto, ipset"
assets = [
    ["target/release/veto", "/usr/bin/veto", "755"],
    ["README.md", "/usr/share/doc/veto/README.md", "644"],
    ["sample.toml", "/etc/veto/config.toml.sample", "644"],
]

[dependencies]
ahash = "0.4.5"
aho-corasick = "0.7.13"
anyhow = "1.0.32"
bincode = "1.3.1"
chrono = { version = "0.4.18", features = ["serde"] }
clap = "3.0.0-beta.2"
crossbeam-channel = "0.4.4"
ctrlc = { version = "3.1.6", features = ["termination"] }
dotenv = "0.15.0"
flate2 = "1.0.17"
humantime = "2.0.1"
ipnetwork = "0.17.0"
itertools = "0.9.0"
log = "0.4.11"
notify = "5.0.0-pre.3"
parking_lot = "0.11.0"
phf = { version = "0.8.0", features = ["macros"] }
pretty_env_logger = "0.4.0"
regex = "1.3.9"
serde = { version = "1.0.116", features = ["derive"] }
toml = "0.5.6"
which = "4.0.2"

[profile.release]
lto = true
panic = "abort"
