[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "AGPL-3.0",
]
allow-osi-fsf-free = "either"

[bans]
skip = [
    { name = "clap", version = "=2.33.3" },
    { name = "humantime", version = "=1.3.0" },
    { name = "textwrap", version = "=0.11.0" },
]
