[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "AGPL-3.0",
]
allow-osi-fsf-free = "either"

[bans]
skip = [
    { name = "bitflags", version = "1" },
]
skip-tree = [
    { name = "windows-sys", version = "0.48", depth = 3 },
]
