# For further instructions see https://github.com/dnaka91/veto.

whitelist = ["192.168.1.0/24"]

[ipset]
target = "Tarpit"

[rules.web]
file = "/etc/logs/access.log"
filters = [
    '^<HOST> - - \[<TIME>\] "<METHOD> (?P<path>/.*) HTTP/\d\.\d" [3-4]\d{2} \d+ "(?P<ref>[^"]+)" "(?P<ua>[^"]+)"',
]
timeout = "3d"

[rules.web.blacklists]
path = [".aspx", ".env", "cgi-bin", "php"]
ua = [
    "dotbot",
    "go-http",
    "googlebot",
    "goscraper",
    "masscan",
    "netcraft",
    "netsystemsresearch",
    "nimbostratus",
    "zgrab",
]
